name: C CI/CD Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test-dist:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install dependencies (GCC + Make)
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # 3️⃣ Build project
      - name: Build project
        run: make all

      # 4️⃣ Run unit tests
      - name: Run unit tests
        run: make check

      # 5️⃣ Publish JUnit test results
      - name: Publish JUnit test results
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'test-reports/test_results.xml'
          include_passed: true
          fail_on_error: false

      # 5️⃣ Run functional/system tests
      - name: Run functional tests
        run: make functional

      # 6️⃣ Full distribution check (build tarball, test from scratch)
      - name: Run distribution check
        run: make distcheck

      # 7️⃣ Upload the .tar.gz source archive as a build artifact
      - name: Upload distribution package
        uses: actions/upload-artifact@v4
        with:
          name: hello-distribution
          path: dist/*.tar.gz
